### ISSUE TITLE
main.js中引入报错了

### ISSUE THREAD

**Issue by songlujie** [vuecmf/vue-vuecmf-dialog#1]
在main.js中引入报错：
ERROR in ./node_modules/vue-vuecmf-dialog/packages/index.ts 21:20
Module parse failed: Unexpected token (21:20)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|  * @param app
|  */
> const install = (app: App):void => {
|   components.forEach(component => {
|     app.use(component.install)
 @ ./src/main.js 25:0-45 43:8-20

**Comment by vuecmf** [comment]
此组件是TypeScript版本的。你的vue项目环境不是TypeScript版本， TypeScript版本的入口文件应该是main.ts， 你的项目入口main.js
